### ISSUE TITLE
A small list

### ISSUE THREAD

**Issue by xZeroW** [Toukibi/ToSAddon#11] opened 2017-07-24 20:09 UTC
Hi, I'm still getting in the mood to translate all other addons (shophelper is already in pt-br, check my pt-br branch), so I bring this list of things that could change.
Shophelper preview:
![0soserh](https://user-images.githubusercontent.com/14045316/28561321-51992614-70f4-11e7-84c9-cb3591bee072.jpg)
By the way, why is this cut?

Feature that could be implemented:

- Option to disable prevent to buy a already running buff

Issue:

- When pressing "space" to talk to a npc in keyboard mode monster list appears

Things to optmize in code:

- SaveTo is never used

- The local CommandParamList could be smaller

```
jp = "日本語モードに切り替え"
en = "Switch to English mode."
kr = "韓国語モードに切り替え (한국어로)"
br = "Trocar para português."
```

Showing the same message no matter what language you are using.

**Comment by Toukibi** [comment] 2017-07-27 16:27
Sorry for the late reply.

Today, the patch was also applied to JToS. And I also confirmed that the setting screen was interrupted.
I'm planning to change ShopHelper.xml also as changing UI of language switching.
  
  
**Option to disable prevent to buy a already running buff**
I'll implement it according to this change
  
  
**When pressing "space" to talk to a npc in keyboard mode monster list appears**
This phenomenon occurs in MapMate and DurNoticeMini.
The specific cause is still unknown, but if you talk to NPC with the system menu open, a popup window will be displayed. If the system menu is closed it will not pop up.
  
  
**The local CommandParamList could be smaller**
These parameters are used in the display of the command list to be called with **`/sh ?`**.
Originally write it as follows.
```
jp = {jp = "日本語モードに切り替え", en = "Switch to Japanese mode.(日本語へ)", kr = "일본어 모드로 전환하십시오.(Japanese Mode)", br = "Trocar para japonês(Japanese Mode)"}

[Name of commands] = {jp = [Notation in the case of Japanese], en = [Notation in the case of English], kr = [Notation in the case of Korean], br = [Notation in the case of pt_br]}
```
In fact it was perfect if it was put together in ResText, but due to the specification of the program, we had to describe the text resource of the command list separately.

**Comment by xZeroW** [comment] 2017-07-27 21:21
Don't worry about not being able to replay fast.

About the option to be able to buy a running buff is really nice to have.
Actually, I had to remove ShopHelper because sometimes I had to wait 5min to buy buffs again.

The others are just minor issues, doesn't really need a fix.

Thanks for your awesome addons. 👍

**Closed as completed** 2017-07-27 21:21 UTC
